### ISSUE TITLE
UISearchBar placeholder missing

### ISSUE THREAD

**Issue by ashchan** [lexrus/LTBouncyPlaceholder#2]
LTBouncyPlaceholder is awesome, but it seems to break `UISearchBar`. When it's used in a project the search bar's placeholder is not showing.

**Comment by lexrus** [comment]
It's unsafe to swizzling drawPlaceholderInRect() of UITextField class. The text field in UISearchBar whose class name is UISearchBarTextField is a subclass of UITextField.
I guess the best practice to use swizzling is not to use it under most circumstances.

**Comment by ashchan** [comment]
@lexrus Agree. Subclass works more safely than extension or swizzling. Thanks for the quick fix!
